version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: clients
    environment:
      POSTGRES_DB: Catalog
      POSTGRES_USER: torreson
      POSTGRES_PASSWORD: p1c4d1nh0100%
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
